services:
  - type: web
    name: tp-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: tp-database
          property: connectionString

databases:
  - name: tp-database
    plan: free
    databaseName: mydb
    user: postgres
